export const GET_COURSE_REQUESTED = "views/login/GET_COURSE_REQUESTED"
export const GET_COURSE_SUCCESS = "views/login/GET_COURSE_SUCCESS"

export const GET_ROOM_REQUESTED = "views/login/GET_ROOM_REQUESTED"
export const GET_ROOM_SUCCESS = "views/login/GET_ROOM_SUCCESS"
export const SELECT_ROOM = "views/login/SELECT_ROOM"

export const REGISTER_ROOM_REQUESTED = "views/login/REGISTER_ROOM_REQUESTED"
export const REGISTER_ROOM_SUCCESS = "views/login/REGISTER_ROOM_SUCCESS"

export const UPDATE_ROOM_REQUESTED = "views/login/UPDATE_ROOM_REQUESTED"
export const UPDATE_ROOM_SUCCESS = "views/login/UPDATE_ROOM_SUCCESS"
export const SELECT_ROOM_DELETE = "views/login/SELECT_ROOM_DELETE"

export const DELETE_ROOM_REQUESTED = "views/login/DELETE_ROOM_REQUESTED"
export const DELETE_ROOM_SUCCESS = "views/login/DELETE_ROOM_SUCCESS"

export const REGISTRATION_LIST_ROOM_REQUESTED =
  "views/login/REGISTRATION_LIST_ROOM_REQUESTED"
export const REGISTRATION_LIS_ROOM_SUCCESS =
  "views/login/REGISTRATION_LIS_ROOM_SUCCESS"

export const GET_ITEM_FAILED = "views/login/GET_ITEM_FAILED"
