export const REGISTRATION_LIST_ROOM_REQUESTED =
  "views/login/REGISTRATION_LIST_ROOM_REQUESTED"
export const REGISTRATION_LIS_ROOM_SUCCESS =
  "views/login/REGISTRATION_LIS_ROOM_SUCCESS"

export const GET_ITEM_FAILED = "views/login/GET_ITEM_FAILED"
